source_db:
  type: postgres
  host: localhost
  port: 5432
  database: corebanking
  user: etl_user
  password: etl_pass

target_db:
  type: postgres
  host: localhost
  port: 5432
  database: datamart
  user: etl_user
  password: etl_pass
